//@ts-nocheck

import Head from "next/head";

import { Home as HomePage } from "@/components";
import { useEffect } from "react";

import cosmic from "@/api/client";

export default function Home() {
  useEffect(() => {
    (async () => {
      await cosmic.objects
        .find({
          type: "posts",
        })
        .limit(1);
    })();
  }, []);
  return (
    <>
      <Head>
        <title>Dom Zdravlja Veliko Gradište</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
